language: python
sudo: true
python:
  - "3.5"
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ubuntu-solutions"
    use_notice: true
    skip_join: true
    on_failure: change
    on_success: never
install:
  - make sysdeps
script:
  - make test
