name: conjure-up
version: 2.0.0.7
summary: Package runtime for conjure-up spells
description: >
   This package provides conjure-up, an interface to installing spells that
   provide the user with an end to end walkthrough experience for installing and
   using big software.
confinement: strict

apps:
  conjure-up:
    command: bin/conjure-up-wrapper
    plugs: [home, network, network-control, network-bind]
  python3:
    command: python3
  shell:
    command: bash

parts:
  conjure:
    plugin: python3
    source: https://github.com/ubuntu/conjure-up.git
    source-type: git
    requirements: requirements.txt
    stage-packages:
      - bsdtar
      - coreutils
      - lxd-client
      - lxd
      - jq
      - juju
    snap:
      - -usr/share
      - -usr/include
      - -home/*/Projects/conjure/snapcraft/parts
  conjure-configs:
    plugin: copy
    source: https://github.com/ubuntu/conjure-up.git
    files:
      etc/conjure-up.conf: etc/conjure-up.conf
      spells: spells
  conjure-up-copy:
    plugin: copy
    source: .
    files:
      conjure-up-wrapper: bin/conjure-up-wrapper
