name: conjure-up
version: 2.1.0
summary: Package runtime for conjure-up spells
description: >
   This package provides conjure-up, an interface to installing spells that
   provide the user with an end to end walkthrough experience for installing and
   using big software.
confinement: classic
grade: stable

apps:
  conjure-up:
    command: wrappers/conjure-up
  conjure-down:
    command: wrappers/conjure-down
    aliases: [conjure-down]
  juju:
    command: wrappers/juju
    aliases: [juju]
  bridge:
    command: wrappers/bridge.start
    stop-command: wrappers/bridge.stop
    restart-condition: never
    daemon: oneshot

parts:
  conjure-up:
    source: .
    plugin: python
    requirements: requirements.txt
    stage-packages:
      - bsdtar
      - jq
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc
      cp etc/conjure-up.conf $SNAPCRAFT_PART_INSTALL/etc/conjure-up.conf
    stage:
      - -README.md
      - -debian
    after: [python]
  spells:
    source: https://github.com/conjure-up/spells.git
    source-type: git
    plugin: dump
    organize:
      "*": spells/
    stage:
      - -README.md
  wrappers:
    plugin: dump
    source: snap/
  juju:
    source: https://github.com/juju/juju.git
    source-type: git
    source-tag: juju-2.1-beta5
    source-depth: 1
    plugin: godeps
    go-importpath: github.com/juju/juju
    go-packages:
      - github.com/juju/juju/cmd/juju
      - github.com/juju/juju/cmd/jujud
  python:
    source: https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
    plugin: autotools
    configflags: [--prefix=/usr]
    build-packages: [libssl-dev]
